### ISSUE TITLE
Import GarageMote Sketch

### ISSUE THREAD

**Issue by kevinklika** [LowPowerLab/GarageMote#1]
Because the GarageMote sketch is a single file and it is decidedly a part of the GarageMote project... Why isn't it in this repo? Same with the other *Motes... I wanted to contribute to the project and submit some pull requests but the location of the sketch right now makes it a little awkward... Is this a bigger discussion, maybe all of the functional sketches should be broken out and the base radio project can just include a vanilla sample sketch instead of a bunch of arguably separate projects?

**Comment by LowPowerLab** [comment]
This is the schematic and board repo, pertains to hardware.
The software is in the RFM69 library along with most other mote example sketches.

**Comment by bepursuant** [comment]
Hi Felix,
I understand how the project is currently structured... What I'm attempting to discuss is restructuring the project(s) a little bit to make them more open-source friendly and modular. I believe each project (GarageMote, SwitchMote, etc) should be it's own repo... I'm not sure how other projects are doing it, but I don't think most publish hardware files in git anyway... ?
Basically, right now your hardware and software pieces are disconnected... I would like to work on this project and contribute pulls, but I feel like the first step is shuffling the project a little bit. I know I can clone down the RFM69 library, but something feels so wrong about that, when my actual interest is, say, GarageMote...

I notice GarageMote software is in LPL/RFM69, but hardware is in LPL/GarageMote... Switchmote software is in LPL/SwitchMote, and I can't find the hardware... Moteino Hardware is in /Moteino but the software is under the wireless module's repo?

Is now a good time to clean up some structural debt and really open this project to the OSS community?

(Sidenote, after watching your video on the beautiful nodejs gateway you created, I'm really excited to get started with my moteinos. You've created a great project here!)

**Comment by LowPowerLab** [comment]
Hi bepursuant,
Thanks for your thoughts, much appreciated. My main issue right now is that all these sketches and repositories are hard linked in a lot of places. Moving anything will break those links.
I am aware the structure is not ideal, and I plan to improve it somehow. I just don't know when's the best time to do that, perhaps when I unify all the devices under the gateway guide that I want to put together.
