### ISSUE TITLE
Board Layout for Hall Sensor

### ISSUE THREAD

**Issue by bepursuant** [LowPowerLab/GarageMote#2]
Hello,

I'm bench testing my garagemote right now, and I was REALLY hoping to be able to use the screw terminals and place the sensors directly in without having to solder any leads right now... but the pinout is different!
On the Board: OUTPUT - GROUND - VCC
On the Sensor: GROUND - OUTPUT - VCC

Not sure if this would be an easy fix, but I think it would be a good iterative change to make building the project a little easier. I have zero experience with Eagle so I can't submit a patch...

**Comment by LowPowerLab** [comment]
Hi,
Actually no, the pinout is in the correct order, the same on the sensor:
https://lowpowerlab.com/shop/sensors/magneticsensor
http://lowpowerlab.com/garagemote/#schematic

**Comment by bepursuant** [comment]
Bah, you even highlighted it... The UA Pin Numbers are in a different order! Well that makes more sense.
