### ISSUE TITLE
Wiring of Relay (Pins 6 and 7)

### ISSUE THREAD

**Issue by bepursuant** [LowPowerLab/GarageMote#3]
As I'm looking at this board and the sketch, I've noticed something that doesn't make a ton of sense to me.

The relay coil appears to be wired to pins 6 and 7... both of which are held HIGH to pulse the relay. The board appears to also ground pin 7 to GND. I would have expected the coil to be connected to one pin and the other pin to GND, but I'm not a hardware guy. 

I assume there is a reason for this?

**Comment by LowPowerLab** [comment]
Explanation here: http://lowpowerlab.com/garagemote/#howitworks

**Comment by bepursuant** [comment]
Details: The relay requires more current than one pin can supply and hence is driven by two digital pins (D6+D7), both of which must be driven HIGH to pulse the relay.
